name : ClashOfClans
main: me.crolemol.coc.Coc
version: 1.0
depends : WorldEdit
commands:
   coc:
      description: This is the main ClashOfClans command.
      usage: /coc [args]
permissions:
    coc.block.break:
         description: Allows you to break blocks in the ClashofClands world
         default: op
    coc.edge.bypass:
         description: Allows you to bypass the arena edges
         default: op